[package]
name = "ccd-wallet"
version.workspace = true
edition.workspace = true

[dependencies]
ccd-wallet-connect = { path = "../ccd-wallet-connect" }
ccd-wallet-core = { path = "../ccd-wallet-core" }
ccd-wallet-identity-provider = { path = "../ccd-wallet-identity-provider" }
ccd-wallet-ledger = { path = "../ccd-wallet-ledger", features = ["hid"] }
ccd-wallet-ledger-governance = { path = "../ccd-wallet-ledger-governance", features = ["sdk"] }
anyhow.workspace = true
base64.workspace = true
bip39.workspace = true
chrono.workspace = true
clap.workspace = true
cliclack.workspace = true
console.workspace = true
concordium-rust-sdk.workspace = true
concordium-smart-contract-engine.workspace = true
ed25519-dalek.workspace = true
futures-util.workspace = true
hex.workspace = true
open.workspace = true
rand.workspace = true
reqwest.workspace = true
reedline.workspace = true
rpassword.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shlex.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
zeroize.workspace = true
