[workspace]
members = ["crates/ccd-wallet-core", "crates/ccd-wallet-identity-provider", "crates/ccd-wallet"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
anyhow = "1.0.102"
argon2 = "0.5.3"
bip39 = { version = "2.2.2", features = ["rand"] }
chacha20poly1305 = "0.10.1"
clap = { version = "4.6.1", features = ["derive", "env"] }
cliclack = "0.5.4"
console = "0.15.11"
concordium-rust-sdk = "9.0.1"
dirs = "6.0.0"
futures-util = "0.3.31"
hex = "0.4.3"
hkdf = "0.12.4"
hmac = "0.12.1"
open = "5.3.2"
rand = "0.8.5"
reqwest = { version = "0.12.24", default-features = false, features = ["blocking", "json", "rustls-tls"] }
sha2 = "0.10.8"
rpassword = "7.5.2"
rusqlite = { version = "0.32.1", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.3", features = ["io-util", "macros", "net", "rt-multi-thread", "signal", "time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt", "json"] }
tonic = { version = "0.12.3", features = ["tls", "tls-native-roots"] }
uuid = { version = "1.12.1", features = ["v4"] }
zeroize = { version = "1.8.1", features = ["derive"] }
