[package]
name = "ccd-wallet-ledger"
version.workspace = true
edition.workspace = true
readme = "README.md"

[features]
default = ["hid"]
sdk = ["dep:concordium-rust-sdk"]
hid = ["dep:hidapi"]

[dependencies]
concordium-rust-sdk = { workspace = true, optional = true }
hidapi = { workspace = true, optional = true }

[dev-dependencies]
anyhow.workspace = true
